# ln -s /Users/peter/Documents/Local/git/.dotfiles/starship/starship.toml /Users/peter/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

format = """
[](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$golang\
$rust\
$python\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
$memory_usage\
[ ](fg:#33658A)\
"""

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[Code King ]($style)'
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'

[memory_usage]
disabled = false
threshold = -1
symbol = ' '
style = 'bg:#33658A'
format = '[$ram_pct ]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[c]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[git_branch]
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[rust]
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[scala]
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[python]
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'
