# ln -s /Users/peter/Documents/Local/git/.dotfiles/starship/starship.toml /Users/peter/.config/starship.toml

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_mocha"

# Inserts a blank line between shell prompts
add_newline = true

format = """
[](green)\
$username\
[](bg:blue fg:green)\
$directory\
[](fg:blue bg:peach)\
$git_branch\
[](fg:peach bg:mauve)\
$time\
[ ](fg:mauve)\
"""

[username]
show_always = true
style_user = "bg:green fg:black"
format = '[~ ]($style)'
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:mauve fg:black"
format = '[ $time ]($style)'

[directory]
style = "bg:blue fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ""

[git_branch]
style = "bg:peach fg:black"
format = '[ $symbol$branch ]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
