#!/bin/bash

selected=$(find ~/Documents/Tails/git ~/Documents/Local/git -mindepth 1 -maxdepth 1 -type d | fzf)
SESSION_NAME=$(basename "$selected" | tr . _)

if [ ! $selected ]; then
  exit 0
fi

# Check if the session already exists
tmux has-session -t $SESSION_NAME 2>/dev/null

if [ $? -eq 0 ]; then
  # If the session exists, reattach to it
  tmux attach -t $SESSION_NAME
else
  # If the session doesn't exist, start a new one
  tmux new -d -s $SESSION_NAME -c $selected "nvim ."
  tmux neww -d -t $SESSION_NAME:2 -c $selected
  tmux neww -d -t $SESSION_NAME:3 -c $selected
  tmux neww -d -t $SESSION_NAME:4 -c $selected
  tmux neww -d -t $SESSION_NAME:5 -c $selected
  tmux attach -t $SESSION_NAME
fi

tmux switch-client -t $SESSION_NAME
